<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class ReadQuestionsTest extends TestCase
{
    use RefreshDatabase;
    private $question;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->question = factory('App\Question')->create([
            'user_id' => factory('App\User')->create()->id
        ]);
    }


    /** @test */
    function a_user_can_read_all_questions()
    {
        $this->get('/questions')
             ->assertSee($this->question->title)
             ->assertSee(str_limit($this->question->title, 200));
    }

    /** @test */
    function a_user_can_view_a_single_question()
    {
        $this->get('/questions/' . $this->question->slug)
             ->assertSee($this->question->title)
             ->assertSee(\Parsedown::instance()->text($this->question->body));
    }






}
